package view;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.CalculatorModel;

/**
 *
 * @author Thiều Văn Tuấn
 */
public class CalculatorView extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorView
     */
    private CalculatorModel Model;

    public CalculatorView(CalculatorModel Model) {
        initComponents();
        setTitle("Tính toán");
        this.Model = Model;
    }

    public CalculatorModel getCalculatorModel() {
        CalculatorModel model = new CalculatorModel();
        String text = jTextField1.getText();
        int index = -1;
        for (int i = 0; i < text.length(); i++) {
            if (i > 0 && Character.isDigit(text.charAt(i - 1)) && text.charAt(i) != '.' && !Character.isDigit(text.charAt(i))) {
                index = i;
                // System.out.println(index);
                break;
            }
        }
        if (index == -1) {
            return model;
        }
        Double firstNumber = Double.parseDouble(text.substring(0, index));
        Double secondNumber = Double.parseDouble(text.substring(index + 1));
//        System.out.println(firstNumber);
//        System.out.println(secondNumber);
        model.setFirstNumber(firstNumber);
        model.setSecondNumber(secondNumber);
        model.setOperator(text.charAt(index));
        return model;
    }

    public void setText(String res) {
        jTextField1.setText(res);
    }

    public String getText() {
        return jTextField1.getText();
    }

    public void shoMessage(String error) {
        JOptionPane.showMessageDialog(this, error);
    }

    public void addButton0Listener(ActionListener log) {
        bt0.addActionListener(log);
    }

    public void addButton1Listener(ActionListener log) {
        bt1.addActionListener(log);
    }

    public void addButton2Listener(ActionListener log) {
        bt2.addActionListener(log);
    }

    public void addButton3Listener(ActionListener log) {
        bt3.addActionListener(log);
    }

    public void addButton4Listener(ActionListener log) {
        bt4.addActionListener(log);
    }

    public void addButton5Listener(ActionListener log) {
        bt5.addActionListener(log);
    }

    public void addButton6Listener(ActionListener log) {
        bt6.addActionListener(log);
    }

    public void addButton7Listener(ActionListener log) {
        bt7.addActionListener(log);
    }

    public void addButton8Listener(ActionListener log) {
        bt8.addActionListener(log);
    }

    public void addButton9Listener(ActionListener log) {
        bt9.addActionListener(log);
    }

    public void addButtonDotListener(ActionListener log) {
        btdot.addActionListener(log);
    }

    public void addButtonClearListener(ActionListener log) {
        btclear.addActionListener(log);
    }

    public void addButtonAddListener(ActionListener log) {
        btadd.addActionListener(log);
    }

    public void addButtonSubListener(ActionListener log) {
        btsub.addActionListener(log);
    }

    public void addButtonMultiListener(ActionListener log) {
        btmul.addActionListener(log);
    }

    public void addButtonDivideListener(ActionListener log) {
        btdiv.addActionListener(log);
    }

    public void addButtonCalculateListener(ActionListener log) {
        btcal.addActionListener(log);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btclear = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        btsub = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btmul = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btcal = new javax.swing.JButton();
        btdiv = new javax.swing.JButton();
        btdot = new javax.swing.JButton();
        btadd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        bt2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt2.setText("2");

        bt3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt3.setText("3");

        btclear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btclear.setForeground(new java.awt.Color(0, 153, 204));
        btclear.setText("C");

        bt1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt1.setText("1");

        bt5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt5.setText("5");

        bt6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt6.setText("6");

        btsub.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btsub.setText("-");

        bt4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt4.setText("4");

        bt8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt8.setText("8");

        bt9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt9.setText("9");

        btmul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btmul.setText("*");

        bt7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt7.setText("7");

        bt0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bt0.setText("0");

        btcal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btcal.setForeground(new java.awt.Color(255, 0, 0));
        btcal.setText("=");

        btdiv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btdiv.setText("/");

        btdot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btdot.setText(".");

        btadd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btadd.setText("+");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btdot, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(228, 228, 228))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(228, 228, 228)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btmul, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(64, 64, 64)
                                    .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btcal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btsub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btadd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btclear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btclear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btadd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btsub, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btmul, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btdot, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorView(new CalculatorModel()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btadd;
    private javax.swing.JButton btcal;
    private javax.swing.JButton btclear;
    private javax.swing.JButton btdiv;
    private javax.swing.JButton btdot;
    private javax.swing.JButton btmul;
    private javax.swing.JButton btsub;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
